[package]
name = "player"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
cpal = "0.17.1"
iced = { version = "0.14.0", features = ["image"] }
symphonia = "0.5.5"
model = { workspace = true }
iced_futures = "0.14.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
